package liir.nlp.nnsrl.features;

/**
 * Created by quynhdo on 02/10/15.
 */
public enum FeatureName {
    Word,
    Pos,
    Lemma,
    Deprel,
    Sense,
    ParentWord,
    ParentPos,
    ParentLemma,
    ParentDeprel,
    RightWord,
    RightPos,
    RightLemma,
    RightDeprel,
    LeftWord,
    LeftPos,
    LeftLemma,
    LeftDeprel,
    RightDepWord,
    RightDepPos,
    RightDepLemma,
    RightDepDeprel,
    LeftDepWord,
    LeftDepPos,
    LeftDepLemma,
    LeftDepDeprel,
    RightSiblingWord,
    RightSiblingPos,
    RightSiblingLemma,
    RightSiblingDeprel,
    LeftSiblingWord,
    LeftSiblingPos,
    LeftSiblingLemma,
    LeftSiblingDeprel,

    PredWord,
    PredPos,
    PredLemma,
    PredDeprel,
    PredSense,

    Position,
    Distance,
    WordDepPath,
    LemmaDepPath,
    PosDepPath,
    DepDepPath,

    ChildDepSet,
    ChildWordSet,
    ChildPosSet,
    ChildLemmaSet,
    ChildWordDepSet,
    ChildPosDepSet,


    DepSubCat,

    WordWE,
    ChildWordSetWE,
    ParentWordWE,

    PredParentWord,
    PredParentPos,
    PredParentLemma,
    PredParentDeprel,

    ChildWordSet_ParentWord,
    DepSubCat_ParentWord,
    ChildWordSet_ParentPos,
    Pos_ParentWord,
    ChildWordSet_Pos,

    Deprel_DepDepPath,
    PosDepPath_RightSiblingPos,
    Deprel_ChildDepSet,
    LeftDepPos_RightDepPos,
    Deprel_PredDeprel,
    Pos_PredSense,
    DepDepPath_Position,
    Deprel_PredParentWord,
    LeftDepPos_PredWord,
    ChildWordSet_PredSense,
    Word_PredSense,
    PosDepPath_PredSense,
    Word_Position,
    PredSense_RightSiblingPos,
    LeftDepPos_RightSiblingPos,
    Pos_Position,
    LeftSiblingPos_PredSense,

    Deprel_PredSense,
    ChildDepSet_Position,
    Deprel_RightDepPos,
    Position_PredSense,
    Pos_Word,
    Pos_PredLemma,
    Deprel_Pos

    }
